postprocess:
  name: ClsPostprocess
  label_list: [ '0','180' ]

eval:
  dataset:
    transform_pipeline:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - RecResizeNormForInfer:
          target_height: 48
          target_width: 192  # 320 for ppocrv3
          keep_ratio: True
          padding: True
          norm_before_pad: True
          mean: [ 0.5, 0.5, 0.5 ]
          std: [ 0.5, 0.5, 0.5 ]
          divisor: 255
          is_hwc: True
      - ToCHWImage:
