system:
  mode: 0 # 0 for graph mode, 1 for pynative mode in MindSpore
  distribute: True
  amp_level: 'O3'
  seed: 42
  log_interval: 100
  val_while_train: True
  drop_overflow_update: False

common:
  character_dict_path: &character_dict_path  #mindocr/utils/dict/en_dict.txt
  num_classes: &num_classes 37 # num_chars_in_dict+1,  TODO: retreive it from dict or check correctness
  max_text_len: &max_text_len 23
  infer_mode: &infer_mode False
  use_space_char: &use_space_char False
  batch_size: &batch_size 16

model:
  type: rec
  transform: null
  backbone:
    name: rec_vgg7
    pretrained: False
  neck:
    name: RNNEncoder
    hidden_size: 256
  head:
    name: CTCHead
    weight_init: crnn_customised
    bias_init: crnn_customised
    out_channels: *num_classes

postprocess:
  name: RecCTCLabelDecode
  character_dict_path: *character_dict_path
  use_space_char: *use_space_char

metric:
  name: RecMetric
  main_indicator: acc
  character_dict_path: *character_dict_path
  ignore_space: True
  print_flag: False

loss:
  name: CTCLoss
  pred_seq_len: 24 # TODO: retrieve from the network output shape.
  max_label_len: *max_text_len  # this value should be smaller than pre_seq_len
  batch_size: *batch_size

scheduler:
  scheduler: warmup_cosine_decay
  min_lr: 0.0
  lr: 0.0005
  num_epochs: 10
  warmup_epochs: 1
  decay_epochs: 9

optimizer:
  opt: adamw
  filter_bias_and_bn: True
  momentum: 0.95
  weight_decay: 0.0001
  nesterov: False
  #use_nesterov: True

loss_scaler:
  type: static
  loss_scale: 1024

train:
  ckpt_save_dir: './tmp_rec'
  pred_cast_fp32: False # let CTCLoss cast internally
  dataset_sink_mode: False
  dataset:
    type: LMDBDataset
    dataset_root: path/to/data_lmdb_release/ # Optional, if set, dataset_root will be used as a prefix for data_dir
    data_dir: training/
    # label_files: # not required when using LMDBDataset
    sample_ratio: 1.0
    shuffle: True
    transform_pipeline:
      - DecodeImage:
          img_mode: BGR
          to_float32: False
      - RecCTCLabelEncode:
          max_text_len: *max_text_len
          character_dict_path: *character_dict_path
          use_space_char: *use_space_char
          lower: True
      - RecResizeImg: # different from paddle (paddle converts image from HWC to CHW and rescale to [-1, 1] after resize.
          image_shape: [32, 100] # H, W
          infer_mode: *infer_mode
          character_dict_path: *character_dict_path
          padding: False # aspect ratio will be preserved if true.
      - NormalizeImage:  # different from paddle (paddle wrongly normalize BGR image with RGB mean/std from ImageNet for det, and simple rescale to [-1, 1] in rec.
          bgr_to_rgb: True
          is_hwc: True
          mean : [127.0, 127.0, 127.0]
          std : [127.0, 127.0, 127.0]
      - ToCHWImage:
    #  the order of the dataloader list, matching the network input and the input labels for the loss function, and optional data for debug/visaulize
    output_columns: ['image', 'text_seq'] #, 'length'] #'img_path']
    net_input_column_index: [0] # input indices for network forward func in output_columns
    label_column_index: [1] # input indices marked as label
    #keys_for_loss: 4 # num labels for loss func

  loader:
      shuffle: True # TODO: tbc
      batch_size: *batch_size
      drop_remainder: True
      max_rowsize: 12
      num_workers: 8

eval:
  ckpt_load_path: './tmp_rec/best.ckpt'
  dataset_sink_mode: False
  dataset:
    type: LMDBDataset
    dataset_root: path/to/data_lmdb_release/
    data_dir: validation/
    # label_files: # not required when using LMDBDataset
    sample_ratio: 1.0
    shuffle: False
    transform_pipeline:
      - DecodeImage:
          img_mode: RGB
          to_float32: False
      - RecCTCLabelEncode:
          max_text_len: *max_text_len
          character_dict_path: *character_dict_path
          use_space_char: *use_space_char
          lower: True
      - RecResizeNormForInfer:
          target_height: 32
          target_width: 100
          keep_ratio: False
          padding: False
          norm_before_pad: False
      - ToCHWImage:
    #  the order of the dataloader list, matching the network input and the input labels for the loss function, and optional data for debug/visaulize
    output_columns: ['image', 'text_padded', 'text_length']  # TODO return text string padding w/ fixed length, and a scaler to indicate the length
    net_input_column_index: [0] # input indices for network forward func in output_columns
    label_column_index: [1, 2] # input indices marked as label

  loader:
      shuffle: False # TODO: tbc
      batch_size: 16
      drop_remainder: False
      max_rowsize: 12
      num_workers: 8
