postprocess:
  name: RecCTCLabelDecode
  use_space_char: True
  blank_at_last: False


eval:
  dataset:
    transform_pipeline:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - RecResizeImg:
          padding: True
      - NormalizeImage:
          mean: [ 127.5, 127.5, 127.5 ]
          std: [ 127.5, 127.5, 127.5 ]
          is_hwc: True
      - ToCHWImage:
