postprocess:
  name: RecCTCLabelDecode
  use_space_char: True
  blank_at_last: False


eval:
  dataset:
    transform_pipeline:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - RecResizeNormForInfer:
          target_height: 48
          target_width: 320
          keep_ratio: True
          padding: True
          norm_before_pad: True
          mean: [ 127.5, 127.5, 127.5 ]
          std: [ 127.5, 127.5, 127.5 ]
      - ToCHWImage:
