postprocess:
  name: RecCTCLabelDecode
  use_space_char: False
  blank_at_last: False

eval:
  dataset:
    transform_pipeline:
      - DecodeImage:
          img_mode: BGR
          channel_first: False
      - RecResizeNormForInfer:
          keep_ratio: True
          padding: True
          norm_before_pad: True
          mean: [127.5, 127.5, 127.5]
          std: [127.5, 127.5, 127.5]
      - ToCHWImage:
