postprocess:
  name: CTCLabelDecode
  use_space_char: True
  use_redundant_space_char: True
  blank_at_last: False

eval:
  dataset:
    transform_pipeline:
      - DecodeImage:
          img_mode: BGR
          channel_first: False
          to_float32: True
      - RecResizeImg:
          padding: True
      - NormalizeImage:
          mean: [ 127.5, 127.5, 127.5 ]
          std: [ 127.5, 127.5, 127.5 ]
          is_hwc: True
      - ToCHWImage:
