postprocess:
  name: CTCLabelDecode
  use_space_char: True
  blank_at_last: False

eval:
  dataset:
    transform_pipeline:
      - DecodeImage:
          img_mode: BGR
          channel_first: False
          to_float32: True
      - CTCLabelEncode:
      - RecResizeImg:
          padding: True
      - ToCHWImage:
