module_order: [ 'dbnet','cls','crnn' ]

device: 'Ascend310P3'
device_id: [ 0 ]

dbnet:
  model_path: './models/dbnet/dbnet_dy_dynamic_shape.om'

cls:
  model_path: './models/cls/cls_310P.om'

crnn:
  model_dir: './models/crnn/static'
  static_method: True
  dict_path: './models/crnn/ppocr_keys_v1.txt'

