system:
  mode: 0 # 0 for graph mode, 1 for pynative mode in MindSpore
  distribute: True
  amp_level: O2
  amp_level_infer: O2 # running inference in O2 mode
  seed: 42
  log_interval: 100
  val_while_train: True
  drop_overflow_update: False
  ckpt_max_keep: 5

common:
  label_list: &label_list ['0', '180']
  num_classes: &num_classes 2

model:
  type: cls
  transform: null
  backbone:
    name: SVTRNet
    pretrained: False
    img_size: [32, 256]
    out_channels: 192
    patch_merging: Conv
    embed_dim: [64, 128, 256]
    depth: [3, 6, 3]
    num_heads: [2, 4, 8]
    mixer:
      [
        "Conv",
        "Conv",
        "Conv",
        "Conv",
        "Conv",
        "Conv",
        "Global",
        "Global",
        "Global",
        "Global",
        "Global",
        "Global",
      ]
    local_mixer: [[5, 5], [5, 5], [5, 5]]
    last_stage: True
    prenorm: False
    use_pos_embed: False
    use_length_scale: True
    length_scale_base: 256
  neck:
    name: Select
    index: 1
  head:
    name: ClsHead
    num_classes: *num_classes

postprocess:
  name: ClsPostprocess
  label_list: *label_list

metric:
  name: ClsMetric
  label_list: *label_list
  main_indicator: acc

loss:
  name: CrossEntropySmooth
  smoothing: 0.1

scheduler:
  scheduler: warmup_cosine_decay
  min_lr: 0.00001
  lr: 0.001
  num_epochs: 10
  warmup_epochs: 1
  decay_epochs: 9

optimizer:
  opt: adamw
  grouping_strategy: svtr
  filter_bias_and_bn: False
  weight_decay: 0.05

# only used for mixed precision training
loss_scaler:
  type: dynamic
  loss_scale: 512
  scale_factor: 2
  scale_window: 1000

train:
  ckpt_save_dir: ./tmp_cls
  dataset_sink_mode: True
  clip_grad: True
  clip_norm: 5.
  exp_op_transform_idx: 1
  dataset:
    type: LMDBDataset
    dataset_root: path/to/data_lmdb_release/
    data_dir: train_single/
    label_file: null
    sample_ratio: 1.0
    shuffle: True
    transform_pipeline:
      - DecodeImage:
          img_mode: RGB
          to_float32: False
      - RecConAug:
          prob: 0.5
          ext_data_num: 2
          image_shape: [32, 256]
          max_text_len: 63
      - NormalizeImage:
          is_hwc: True
          mean: [127.0, 127.0, 127.0]
          std: [127.0, 127.0, 127.0]
      - SSLRotateResize:
          image_shape: [32, 256]
          padding: True
          select_all: False
      - ToCHWImage:
    collate_fn:
      SSLRotateCollate:
        shuffle: True
    output_columns: ["image", "label"]
    net_input_column_index: [0]
    label_column_index: [1]

  loader:
    shuffle: True
    batch_size: 512
    drop_remainder: True
    max_rowsize: 12
    num_workers: 4

eval:
  ckpt_load_path: ./tmp_cls/best.ckpt
  dataset_sink_mode: False
  dataset:
    type: LMDBDataset
    dataset_root: path/to/data_lmdb_release/
    data_dir: val/
    label_file: null
    sample_ratio: 1.0
    shuffle: False
    transform_pipeline:
      - DecodeImage:
          img_mode: RGB
          to_float32: False
      - NormalizeImage:
          is_hwc: True
          mean: [127.0, 127.0, 127.0]
          std: [127.0, 127.0, 127.0]
      - SSLRotateResize:
          image_shape: [32, 256]
          padding: True
          select_all: False
      - ToCHWImage:
    collate_fn:
      SSLRotateCollate:
        shuffle: False
    output_columns: ["image", "label"]
    net_input_column_index: [0]
    label_column_index: [1]

  loader:
    shuffle: False
    batch_size: 512
    drop_remainder: False
    max_rowsize: 12
    num_workers: 4
