#ifndef DEPLOY_CPP_INFER_SRC_BASE_STATUS_CODE_STATUS_CODE_H_
#define DEPLOY_CPP_INFER_SRC_BASE_STATUS_CODE_STATUS_CODE_H_

enum class Status {
    FAILURE = -1,
    OK = 0,
    QUEUE_STOPPED = 1,
    QUEUE_EMPTY = 2,
    QUEUE_FULL = 3,
    COMM_EXIST = 4,
    COMM_NO_EXIST = 5,
    COMM_INVALID_PARAM = 6,
    COMM_FAILURE = 7,
    INTERNAL_ERROR = 8,
    UNSUPPORTED_INFER_ENGINE = 9,
    LITE_MODEL_BUILD_FAILURE = 10,
    LITE_MODEL_INFER_FAILURE = 11,
    MINDX_MODEL_INFER_FAILURE = 12,
    UNSUPPORTED_TASK_TYPE = 13
};

#endif
